// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_texture
arma::cube calc_texture(arma::mat rast, int n_grey, arma::rowvec window_dims, arma::mat shift, Rcpp::CharacterVector statistics, std::string na_opt, double na_val);
RcppExport SEXP glcm_calc_texture(SEXP rastSEXP, SEXP n_greySEXP, SEXP window_dimsSEXP, SEXP shiftSEXP, SEXP statisticsSEXP, SEXP na_optSEXP, SEXP na_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type rast(rastSEXP);
    Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type window_dims(window_dimsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type statistics(statisticsSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_opt(na_optSEXP);
    Rcpp::traits::input_parameter< double >::type na_val(na_valSEXP);
    __result = Rcpp::wrap(calc_texture(rast, n_grey, window_dims, shift, statistics, na_opt, na_val));
    return __result;
END_RCPP
}
